/**
 * iddl
 * 
 * Intelligent Distributed Data Layer
 * 
 * iddl-group-datasource
 */
package com.it.iddl.group.jdbc;

import java.io.InputStream;
import java.io.Reader;
import java.net.URL;
import java.sql.Connection;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.it.iddl.common.jdbc.ParameterContext;
import com.it.iddl.common.jdbc.ParameterMethod;
import com.it.iddl.common.parameter.Parameters;
import com.it.iddl.group.AbstractGroupDataSource;
import com.it.iddl.group.dbselector.DBSelector;
import com.it.iddl.group.dbselector.DBSelector.AbstractDataSourceTryer;
import com.it.iddl.group.dbselector.DBSelector.DataSourceTryer;
import com.it.iddl.group.dbselector.ThreadLocalDataSourceIndex;
import com.it.iddl.util.GroupHintParser;

/**
 * 
 * @author sihai
 *
 */
public class GroupPreparedStatement extends GroupStatement implements PreparedStatement {

	private static final Log logger = LogFactory.getLog(GroupPreparedStatement.class);

	private String sql;
	private int autoGeneratedKeys = -1;
	private int[] columnIndexes;
	private String[] columnNames;
	//参数列表到参数上下文的映射  如 1:name  2：'2011-11-11'
	protected Map<Integer, ParameterContext> parameterSettings = new HashMap<Integer, ParameterContext>();
	
	public GroupPreparedStatement(AbstractGroupDataSource groupDataSource, GroupConnection groupConnection, String sql) {
		super(groupDataSource, groupConnection);
		this.sql = sql;
	}
	
	private PreparedStatement createPreparedStatementInternal(Connection conn, String sql) throws SQLException {
		PreparedStatement ps;
		if (autoGeneratedKeys != -1) {
			ps = conn.prepareStatement(sql, autoGeneratedKeys);
		} else if (columnIndexes != null) {
			ps = conn.prepareStatement(sql, columnIndexes);
		} else if (columnNames != null) {
			ps = conn.prepareStatement(sql, columnNames);
		} else {
			int resultSetHoldability = this.resultSetHoldability;
			if (resultSetHoldability == -1) //未调用过setResultSetHoldability
				resultSetHoldability = conn.getHoldability();

			ps = conn.prepareStatement(sql, this.resultSetType, this.resultSetConcurrency, resultSetHoldability);
		}
		setBaseStatement(ps);
		ps.setQueryTimeout(queryTimeout); //这句可能抛出异常，所以要放到setBaseStatement之后
	    ps.setFetchSize(fetchSize);
	    ps.setMaxRows(maxRows);

		return ps;
	}
	
	public void clearParameters() throws SQLException {
		parameterSettings.clear();
	}

	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
		parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setTimestamp2, new Object[] {
				parameterIndex, x, cal }));
	}

	public void setURL(int parameterIndex, URL x) throws SQLException {
		parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setURL, new Object[] {
				parameterIndex, x }));
	}

	@Deprecated
	public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
		parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setUnicodeStream, new Object[] {
				parameterIndex, x, length }));
	}

	/* ========================================================================
	 * executeBatch
	 * ======================================================================*/
	private List<Map<Integer, ParameterContext>> pstArgs;

	public void addBatch() throws SQLException {
		if (pstArgs == null) {
			pstArgs = new LinkedList<Map<Integer, ParameterContext>>();
		}
		Map<Integer, ParameterContext> newArg = new HashMap<Integer, ParameterContext>(parameterSettings.size());
		newArg.putAll(parameterSettings);

		parameterSettings.clear();

		pstArgs.add(newArg);
	}

	public int[] executeBatch() throws SQLException {
		try {
			checkClosed();
			ensureResultSetIsClosed();

			if (pstArgs == null || pstArgs.isEmpty()) {
				return new int[0];
			}

			Connection conn = groupConnection.getBaseConnection(sql,false);

			if (conn != null) {
				sql=GroupHintParser.removeTddlGroupHint(sql);
				// 如果当前已经有连接,则不做任何重试。对于更新来说，不管有没有事务，
				// 用户总期望getConnection获得连接之后，后续的一系列操作都在这同一个库，同一个连接上执行
				return executeBatchOnConnection(conn);
			} else {
				Integer dataSourceIndex = GroupHintParser.convertHint2Index(sql, DBSelector.NOT_EXIST_USER_SPECIFIED_INDEX);
				sql=GroupHintParser.removeTddlGroupHint(sql);
				if (dataSourceIndex < 0) {
					dataSourceIndex = ThreadLocalDataSourceIndex.getIndex();
				}
				return groupDataSource.getDBSelector(false).tryExecute(null, executeBatchTryer, retryTimes,dataSourceIndex);
			}
		} finally {
			if (pstArgs != null)
				pstArgs.clear();
		}
	}

	private DataSourceTryer<int[]> executeBatchTryer = new AbstractDataSourceTryer<int[]>() {
		public int[] tryOnDataSource(GroupDataSourceWrapper dsw, Object... args) throws SQLException {
			Connection conn = groupConnection.createNewConnection(dsw, false);
			return executeBatchOnConnection(conn);
		}
	};

	//TODO 重试中Statement的关闭
	private int[] executeBatchOnConnection(Connection conn) throws SQLException {
		PreparedStatement ps = createPreparedStatementInternal(conn, sql);

		for (Map<Integer, ParameterContext> parameterSettings : pstArgs) {
			setBatchParameters(ps, parameterSettings.values());
			ps.addBatch();
		}

		return ps.executeBatch();
	}

	private static void setBatchParameters(PreparedStatement ps, Collection<ParameterContext> batchedParameters)
			throws SQLException {
		for (ParameterContext context : batchedParameters) {
			Parameters.parameterHandlers.get(context.getParameterMethod()).setParameter(ps, context.getArgs());
		}
	}

	/* ========================================================================
	 * 无逻辑的getter/setter
	 * ======================================================================*/
	public int getAutoGeneratedKeys() {
		return autoGeneratedKeys;
	}

	public void setAutoGeneratedKeys(int autoGeneratedKeys) {
		this.autoGeneratedKeys = autoGeneratedKeys;
	}

	public int[] getColumnIndexes() {
		return columnIndexes;
	}

	public void setColumnIndexes(int[] columnIndexes) {
		this.columnIndexes = columnIndexes;
	}

	public String[] getColumnNames() {
		return columnNames;
	}

	public void setColumnNames(String[] columnNames) {
		this.columnNames = columnNames;
	}

	public boolean isClosed() throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setPoolable(boolean poolable) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public boolean isPoolable() throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public <T> T unwrap(Class<T> iface) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setRowId(int parameterIndex, RowId x) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setNString(int parameterIndex, String value)
			throws SQLException
	{
		throw new SQLException("not support exception");

	}

	public void setNCharacterStream(int parameterIndex, Reader value,
			long length) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setNClob(int parameterIndex, NClob value) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setClob(int parameterIndex, Reader reader, long length)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setBlob(int parameterIndex, InputStream inputStream, long length)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setNClob(int parameterIndex, Reader reader, long length)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setSQLXML(int parameterIndex, SQLXML xmlObject)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setAsciiStream(int parameterIndex, InputStream x, long length)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setBinaryStream(int parameterIndex, InputStream x, long length)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setCharacterStream(int parameterIndex, Reader reader,
			long length) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setAsciiStream(int parameterIndex, InputStream x)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setBinaryStream(int parameterIndex, InputStream x)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setCharacterStream(int parameterIndex, Reader reader)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setNCharacterStream(int parameterIndex, Reader value)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setClob(int parameterIndex, Reader reader) throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setBlob(int parameterIndex, InputStream inputStream)
			throws SQLException
	{
		throw new SQLException("not support exception");
	}

	public void setNClob(int parameterIndex, Reader reader) throws SQLException
	{
		throw new SQLException("not support exception");
	}
}
